[versions]
core = "1.8.0"
kotlinBom = "1.8.0"
lifecycleRuntime = "2.3.1"
activityCompose = "1.5.1"
composeBom = "2022.10.00"
material3 = "1.1.2"
retrofit2 = "2.9.0"
viewmodelCompose = "2.6.2"
ktor = "2.3.7"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlinBom" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime", version.ref = "lifecycleRuntime" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2" }
viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "viewmodelCompose" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-json-jvm = { group = "io.ktor", name = "ktor-client-json-jvm", version.ref = "ktor" }
ktor-serialization-gson = { group = "io.ktor", name = "ktor-serialization-gson", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }

[bundles]
retrofit = ["retrofit2", "converter-gson"]
ktor = [
    "ktor-client-core",
    "ktor-client-android",
    "ktor-client-json-jvm",
    "ktor-serialization-gson",
    "ktor-serialization-json",
    "ktor-client-logging",
    "ktor-client-content-negotiation",
]