[versions]
core = "1.8.0"
kotlinBom = "1.8.0"
lifecycleRuntime = "2.3.1"
activityCompose = "1.5.1"
composeBom = "2022.10.00"
material3 = "1.1.2"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlinBom" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime", version.ref = "lifecycleRuntime" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

[bundles]
